"""add opening_balance columns to accounts

Revision ID: 9b6fe7b42587
Revises: 5f3a0c10d3e5
Create Date: 2026-04-03 09:35:42.666726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6fe7b42587'
down_revision: Union[str, Sequence[str], None] = '5f3a0c10d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('accounts', sa.Column('opening_balance_date', sa.Date(), nullable=True))
    op.add_column('investment_transfers', sa.Column('units_added', sa.DECIMAL(precision=15, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transfers', 'units_added')
    op.drop_column('accounts', 'opening_balance_date')
    op.drop_column('accounts', 'opening_balance')
    # ### end Alembic commands ###
