"""initial schema

Revision ID: a87508b6f04d
Revises: 
Create Date: 2025-11-11 23:28:31.368171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a87508b6f04d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('calculation_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finalized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'FINALIZED', 'ARCHIVED')", name='check_status'),
    sa.CheckConstraint('end_date >= start_date', name='valid_date_range'),
    sa.CheckConstraint('snapshot_date = end_date', name='valid_snapshot_date'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_periods_status', 'calculation_periods', ['user_id', 'status'], unique=False)
    op.create_index('idx_periods_user', 'calculation_periods', ['user_id'], unique=False)
    op.create_index('idx_periods_user_date', 'calculation_periods', ['user_id', 'snapshot_date'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='unique_ticker_per_user')
    )
    op.create_index('idx_currencies_default', 'currencies', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_currencies_user', 'currencies', ['user_id'], unique=False)
    op.create_table('custom_expense_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type_name', name='unique_type_per_user')
    )
    op.create_index('idx_custom_types_user', 'custom_expense_types', ['user_id'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('is_system_category', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_active', 'expense_categories', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_categories_parent', 'expense_categories', ['parent_category_id'], unique=False)
    op.create_index('idx_categories_sort', 'expense_categories', ['user_id', 'sort_order'], unique=False)
    op.create_index('idx_categories_user', 'expense_categories', ['user_id'], unique=False)
    op.create_table('investment_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('BROKERAGE', 'CRYPTO_EXCHANGE', 'PHYSICAL')", name='check_investment_account_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investment_accounts_active', 'investment_accounts', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_investment_accounts_user', 'investment_accounts', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("template_type IN ('EXPENSE_CATEGORIES', 'INCOME_SOURCES', 'FULL')", name='check_template_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_templates_data', 'templates', ['template_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_templates_default', 'templates', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_templates_type', 'templates', ['user_id', 'template_type'], unique=False)
    op.create_index('idx_templates_user', 'templates', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('BANK', 'CASH')", name='check_account_type'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_accounts_active', 'accounts', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_accounts_currency', 'accounts', ['currency_id'], unique=False)
    op.create_index('idx_accounts_user', 'accounts', ['user_id'], unique=False)
    op.create_table('expense_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=False),
    sa.Column('tax_category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("expense_type IN ('REGULAR', 'INSTALLMENT_PAYMENT')", name='check_expense_type'),
    sa.CheckConstraint('amount >= 0', name='positive_expense_amount'),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_category', 'expense_items', ['category_id'], unique=False)
    op.create_index('idx_expenses_currency', 'expense_items', ['currency_id'], unique=False)
    op.create_index('idx_expenses_date', 'expense_items', ['expense_date'], unique=False)
    op.create_index('idx_expenses_period', 'expense_items', ['calculation_period_id'], unique=False)
    op.create_index('idx_expenses_tax_deductible', 'expense_items', ['calculation_period_id', 'is_tax_deductible'], unique=False)
    op.create_table('income_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=True),
    sa.Column('tax_applicable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='positive_income_amount'),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_income_currency', 'income_entries', ['currency_id'], unique=False)
    op.create_index('idx_income_date', 'income_entries', ['income_date'], unique=False)
    op.create_index('idx_income_period', 'income_entries', ['calculation_period_id'], unique=False)
    op.create_table('installment_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('initial_period_id', sa.UUID(), nullable=False),
    sa.Column('remaining_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('monthly_payment_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('months_to_pay', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'PAID_OFF')", name='check_installment_status'),
    sa.CheckConstraint('remaining_balance >= 0', name='check_remaining_balance_positive'),
    sa.CheckConstraint('total_price > 0', name='check_total_price_positive'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initial_period_id'], ['calculation_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_installments_period', 'installment_items', ['initial_period_id'], unique=False)
    op.create_index('idx_installments_status', 'installment_items', ['user_id', 'status'], unique=False)
    op.create_index('idx_installments_user', 'installment_items', ['user_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('investment_account_id', sa.UUID(), nullable=True),
    sa.Column('opening_balance', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('opening_balance_currency_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_account_id'], ['investment_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_balance_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investments_account', 'investments', ['investment_account_id'], unique=False)
    op.create_index('idx_investments_category', 'investments', ['user_id', 'category_name'], unique=False)
    op.create_index('idx_investments_user', 'investments', ['user_id'], unique=False)
    op.create_table('suspended_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_period_id', sa.UUID(), nullable=False),
    sa.Column('settled_period_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'SETTLED', 'CONVERTED_TO_EXPENSE')", name='check_suspended_status'),
    sa.CheckConstraint("transaction_type IN ('LOAN_OUT', 'PURCHASE_RETURN', 'OTHER')", name='check_transaction_type'),
    sa.CheckConstraint('amount >= 0', name='positive_suspended_amount'),
    sa.ForeignKeyConstraint(['created_period_id'], ['calculation_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settled_period_id'], ['calculation_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suspended_created_period', 'suspended_expenses', ['created_period_id'], unique=False)
    op.create_index('idx_suspended_settled_period', 'suspended_expenses', ['settled_period_id'], unique=False)
    op.create_index('idx_suspended_status', 'suspended_expenses', ['status', 'created_period_id'], unique=False)
    op.create_index('idx_suspended_user', 'suspended_expenses', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_currency_id', sa.UUID(), nullable=False),
    sa.Column('tax_system', sa.String(length=50), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('preferred_date_format', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tax_system IN ('POLISH_B2B', 'US_ANNUAL', 'NONE')", name='check_tax_system'),
    sa.CheckConstraint('tax_rate >= 0 AND tax_rate <= 100', name='check_tax_rate'),
    sa.ForeignKeyConstraint(['default_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('balance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'calculation_period_id', name='unique_account_period')
    )
    op.create_index('idx_snapshots_account', 'balance_snapshots', ['account_id'], unique=False)
    op.create_index('idx_snapshots_date', 'balance_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshots_period', 'balance_snapshots', ['calculation_period_id'], unique=False)
    op.create_table('currency_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('from_currency_id', sa.UUID(), nullable=False),
    sa.Column('to_currency_id', sa.UUID(), nullable=False),
    sa.Column('from_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('to_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('conversion_date', sa.Date(), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_amount > 0', name='check_from_amount_positive'),
    sa.CheckConstraint('from_currency_id <> to_currency_id', name='different_currencies'),
    sa.CheckConstraint('rate > 0', name='check_conversion_rate_positive'),
    sa.CheckConstraint('to_amount > 0', name='check_to_amount_positive'),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversions_date', 'currency_conversions', ['conversion_date'], unique=False)
    op.create_index('idx_conversions_from_currency', 'currency_conversions', ['from_currency_id'], unique=False)
    op.create_index('idx_conversions_period', 'currency_conversions', ['calculation_period_id'], unique=False)
    op.create_index('idx_conversions_to_currency', 'currency_conversions', ['to_currency_id'], unique=False)
    op.create_table('installment_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installment_item_id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('payment_amount > 0', name='check_payment_amount_positive'),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installment_item_id'], ['installment_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_date', 'installment_payments', ['payment_date'], unique=False)
    op.create_index('idx_payments_installment', 'installment_payments', ['installment_item_id'], unique=False)
    op.create_index('idx_payments_period', 'installment_payments', ['calculation_period_id'], unique=False)
    op.create_table('investment_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('calculation_period_id', sa.UUID(), nullable=False),
    sa.Column('amount_transferred', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('is_opening_balance', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_period_id'], ['calculation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transfers_currency', 'investment_transfers', ['currency_id'], unique=False)
    op.create_index('idx_transfers_date', 'investment_transfers', ['transfer_date'], unique=False)
    op.create_index('idx_transfers_investment', 'investment_transfers', ['investment_id'], unique=False)
    op.create_index('idx_transfers_opening', 'investment_transfers', ['is_opening_balance'], unique=False)
    op.create_index('idx_transfers_period', 'investment_transfers', ['calculation_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transfers_period', table_name='investment_transfers')
    op.drop_index('idx_transfers_opening', table_name='investment_transfers')
    op.drop_index('idx_transfers_investment', table_name='investment_transfers')
    op.drop_index('idx_transfers_date', table_name='investment_transfers')
    op.drop_index('idx_transfers_currency', table_name='investment_transfers')
    op.drop_table('investment_transfers')
    op.drop_index('idx_payments_period', table_name='installment_payments')
    op.drop_index('idx_payments_installment', table_name='installment_payments')
    op.drop_index('idx_payments_date', table_name='installment_payments')
    op.drop_table('installment_payments')
    op.drop_index('idx_conversions_to_currency', table_name='currency_conversions')
    op.drop_index('idx_conversions_period', table_name='currency_conversions')
    op.drop_index('idx_conversions_from_currency', table_name='currency_conversions')
    op.drop_index('idx_conversions_date', table_name='currency_conversions')
    op.drop_table('currency_conversions')
    op.drop_index('idx_snapshots_period', table_name='balance_snapshots')
    op.drop_index('idx_snapshots_date', table_name='balance_snapshots')
    op.drop_index('idx_snapshots_account', table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_table('user_settings')
    op.drop_index('idx_suspended_user', table_name='suspended_expenses')
    op.drop_index('idx_suspended_status', table_name='suspended_expenses')
    op.drop_index('idx_suspended_settled_period', table_name='suspended_expenses')
    op.drop_index('idx_suspended_created_period', table_name='suspended_expenses')
    op.drop_table('suspended_expenses')
    op.drop_index('idx_investments_user', table_name='investments')
    op.drop_index('idx_investments_category', table_name='investments')
    op.drop_index('idx_investments_account', table_name='investments')
    op.drop_table('investments')
    op.drop_index('idx_installments_user', table_name='installment_items')
    op.drop_index('idx_installments_status', table_name='installment_items')
    op.drop_index('idx_installments_period', table_name='installment_items')
    op.drop_table('installment_items')
    op.drop_index('idx_income_period', table_name='income_entries')
    op.drop_index('idx_income_date', table_name='income_entries')
    op.drop_index('idx_income_currency', table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_index('idx_expenses_tax_deductible', table_name='expense_items')
    op.drop_index('idx_expenses_period', table_name='expense_items')
    op.drop_index('idx_expenses_date', table_name='expense_items')
    op.drop_index('idx_expenses_currency', table_name='expense_items')
    op.drop_index('idx_expenses_category', table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_index('idx_accounts_user', table_name='accounts')
    op.drop_index('idx_accounts_currency', table_name='accounts')
    op.drop_index('idx_accounts_active', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('idx_templates_user', table_name='templates')
    op.drop_index('idx_templates_type', table_name='templates')
    op.drop_index('idx_templates_default', table_name='templates')
    op.drop_index('idx_templates_data', table_name='templates', postgresql_using='gin')
    op.drop_table('templates')
    op.drop_index('idx_investment_accounts_user', table_name='investment_accounts')
    op.drop_index('idx_investment_accounts_active', table_name='investment_accounts')
    op.drop_table('investment_accounts')
    op.drop_index('idx_categories_user', table_name='expense_categories')
    op.drop_index('idx_categories_sort', table_name='expense_categories')
    op.drop_index('idx_categories_parent', table_name='expense_categories')
    op.drop_index('idx_categories_active', table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_index('idx_custom_types_user', table_name='custom_expense_types')
    op.drop_table('custom_expense_types')
    op.drop_index('idx_currencies_user', table_name='currencies')
    op.drop_index('idx_currencies_default', table_name='currencies')
    op.drop_table('currencies')
    op.drop_index('idx_periods_user_date', table_name='calculation_periods')
    op.drop_index('idx_periods_user', table_name='calculation_periods')
    op.drop_index('idx_periods_status', table_name='calculation_periods')
    op.drop_table('calculation_periods')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
